#!/usr/bin/env bash

# Copyright 2021 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

# cd to the repo root so the bin/ cache, the directory walk, and the relative
# --skip path below are all anchored to the repo root regardless of the caller's
# working directory.
cd "$(git rev-parse --show-toplevel)"

VERSION=v0.2.6
URL_BASE=https://raw.githubusercontent.com/kubernetes/repo-infra
URL=$URL_BASE/$VERSION/hack/verify_boilerplate.py
BIN_DIR=bin
# Include the version in the cached filename so a version bump forces a fresh
# download. bin/ is gitignored and persists across runs/branches, so a plain
# fixed name would silently reuse a stale older script (e.g. a cached v0.2.0
# that still requires the YEAR placeholder this change removed).
SCRIPT=$BIN_DIR/verify_boilerplate-$VERSION.py

if [[ ! -f $SCRIPT ]]; then
    mkdir -p $BIN_DIR
    curl -sfL $URL -o $SCRIPT
    chmod +x $SCRIPT
fi

# api/apifakes contains counterfeiter-generated files (// Code generated by
# counterfeiter. DO NOT EDIT.) that carry no copyright header.
$SCRIPT --boilerplate-dir hack/boilerplate --skip api/apifakes
