@startuml
!theme reddress-lightblue

(*) -->[ **user** creates Pod with inline ResourceClaimTemplate ] "Pod exists"
-->[ **resource controller** checks ResourceClaimTemplate and ResourceClass,\l then creates ResourceClaim with Pod as owner ] ==B1==

==B1== -->[= __immediate allocation__] "ResourceClaim\lfor immediate allocation with\l* phase=pending\l* plugin name set"
  -->[ **resource plugin**\l updates claim\l to prevent deletion] "ResourceClaim\lfor immediate allocation\lwith finalizer"
  -->[ **resource plugin**\l finishes allocation] "ResourceClaim with\l* phase=allocated\n* Attributes and UserLimit set" as ALLOCATED


==B1== -->[= __delayed allocation__] "ResourceClaim\lfor delayed allocation with\l* phase=pending\l* plugin name set"
  -->[ **scheduler** filters nodes\l and sets PotentialNodes ] "ResourceClaim\lfor delayed allocation with\l* phase=pending\l* PotentialNodes set"
  -->[ **resource controller** checks nodes\l and sets SuitableNodes] "ResourceClaim with\l* phase=pending\l* SuitableNodes set" as READY_FOR_SCHEDULING
  -->[ **scheduler** picks a node candidate ] "ResourceClaim with\l* phase=pending\l* SelectedNode set"
  -->[ **resource plugin**\l updates claim\l to prevent deletion] "ResourceClaim\lfor delayed allocation\lwith finalizer" as ALLOCATING
  -->[ **resource plugin**\l finishes allocation ] ALLOCATED

  ALLOCATING -->[ **resource plugin**\l detects that resource cannot be allocated for node\n and removes SelectedNode and finalizer ] READY_FOR_SCHEDULING

ALLOCATED -->[ **scheduler** reserves resource for pod ]  "ResourceClaim\lwith one additional UsedBy entry"
-->[ **scheduler** schedules pod ] "Pod ready to run"
-->[ **kubelet** calls NodePrepareResource\l and adds CDI devices for the runtime ] "Pod runs"
-->[ Pod stops, gets deleted\l **garbage collector** marks ResourceClaim for deletion ] "ResourceClaim with\l* deletion timestamp\l* UsedBy non-empty"
-->[ **resource controller** removes deleted Pod from UsedBy ] "ResourceClaim with\l* deletion timestamp\l* UsedBy empty"
-->[ **resource plugin** finishes deallocation ] "ResourceClaim\l* with deletion timestamp\l* without finalizer\l* phase=freed"
-->[ **garbage collector** deletes ResourceClaim ] (*)
@enduml
