@startuml
!theme reddress-lightblue
skinparam componentStyle rectangle

cloud "resource driver" {
  component "resource driver controller" as drivercontroller
  component "resource kubelet plugin" as driverplugin
}

component Kubernetes {
  component apiserver {
      file Pod
      file "..." as otherapi
      file ResourceClaim
  }
  component scheduler {
    component "resource plugin" as k8sresourceplugin
  }
  component "controller-manager" as controllermanager {
    component "resource claim controller" as k8sresourceclaimcontroller
  }
  component kubelet {
    component "plugin manager" as pluginmanager
    component "resource manager" as resourcemanager
  }
}

drivercontroller -[hidden]> driverplugin
Pod -[hidden]> otherapi
otherapi -[hidden]> ResourceClaim

Pod -u-> k8sresourceclaimcontroller: read resource template\nfrom Pod spec
ResourceClaim <-u- k8sresourceclaimcontroller: create

Pod <--> scheduler
ResourceClaim <--> k8sresourceplugin

ResourceClaim <-> drivercontroller
pluginmanager <-> driverplugin
resourcemanager <-> driverplugin
@enduml
